// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type User struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	Age      int32  `json:"age"`
	Password string `json:"password"`
}
